PYTHON := $(shell if command -v uv >/dev/null 2>&1; then echo "uv run python3"; else echo "python3"; fi)

d1: 
	$(PYTHON) task_d1.py

d2:
	$(PYTHON) task_d2.py

d3:
	$(PYTHON) task_d3.py

d4:
	$(PYTHON) task_d4.py

d5:
	$(PYTHON) task_d5.py

d6:
	$(PYTHON) task_d6.py

d7:
	$(PYTHON) task_d7.py

