d1: 
	uv run python3 task_d1.py

d2:
	uv run python3 task_d2.py

d3:
	uv run python3 task_d3.py

d4:
	uv run python3 task_d4.py

d5:
	uv run python3 task_d5.py

d6:
	uv run python3 task_d6.py

d7:
	uv run python3 task_d7.py

