
c3:
	uv run python3 main.py --IconDataset ./IconDataset/png/ --Task3Dataset ./Task3Dataset/
	@feh -d output

c3-search:
	uv run python3 main.py --IconDataset ./IconDataset/png/ --GridSearch ./Task3Dataset/

clean:
	rm -f output/*
